### ISSUE TITLE
Is cutting a polygon with "holes" is supported ?

### ISSUE THREAD

**Issue by dorli** [alexbol99/flatten-js#102]
Hey,
I'm trying to cut a polygon that has a hole (different faces that have different orientations) but I'm getting an exception.
I can't find an example of doing this in the tutorials or the tests, is that supposed to work?

**Comment by alexbol99** [comment]
Hi, @dorli 
You are right, current implementation does not support polygon with holes. I will update it in a nearest future
Do you need a method that cut polygon with a line or something more complicated?
Best regards,
Alex

**Comment by alexbol99** [comment]
Hi @dorli ,
I added new method ```polygon.cutWithLine``` to release v1.3.2 but it still buggy.
You can play with this method here: [observablehq.com/@alexbol99/cut-polygon-with-line](url)

**Comment by dorli** [comment]
Hi @alexbol99,
First of all, thank you very much for the quick response and for this great library.
I'm going to try the new method.

**Comment by alexbol99** [comment]
Hi @dorli ,
I released new patch 1.3.3 with 2 bugs fixed for this method.
Would be nice if you could test it.
Alex
