### ISSUE TITLE
Full documentation it's broken

### ISSUE THREAD

**Issue by giannaccio** [alexbol99/flatten-js#11]
Since few days the links inside documentation are broken
https://alexbol99.github.io/flatten-js/Flatten.html#.Box
https://alexbol99.github.io/flatten-js/Flatten.html#.Arc

The link https://alexbol99.github.io/flatten-js/Flatten.html give me 404 error

**Comment by alexbol99** [comment]
Documentation was fixed.
Thank you @giannaccio for pointing on that.
