### ISSUE TITLE
Intersect ray with ray or line

### ISSUE THREAD

**Issue by edemaine** [alexbol99/flatten-js#129]
`Ray`'s `intersect` method supports `Segment` and `Arc`, but not `Ray` or `Line`.  I'd hope this is pretty similar to `intersectSegment2Segment`.

Related, `Point`'s `on` method doesn't support `Ray` arguments. Instead we need to use `Ray`'s `contains` method.

**Comment by alexbol99** [comment]
Hi, @edemaine 
Intersection ray with other shaped supported in v1.4.1
