### ISSUE TITLE
Typescript error?

### ISSUE THREAD

**Issue by BraunTom** [alexbol99/flatten-js#14]
Maybe it is because I am inexperienced with Typescript, but if you import something in Typescript it tries to load the default property of the exported object, which gives me the error:

   new flatten_js_1.default.Point(x, y);
TypeError: Cannot read property 'Point' of undefined 

because in the index.js is only module.exports = f (if I change it to 
    module.exports.default = f; 
it fixes the problem for me)

**Comment by SamuelQZQ** [comment]
I have the same problem.

`import Flatten from 'flatten-js';`

When I import like this in Typescript, Flatten is undefined.

In the index.js, if I change `module.exports = f` to `module.exports.default = f` fixes the problem for me.

But I think that's not the best solution.

**Comment by OldrichDlouhy** [comment]
Use the following syntax for import flatten in Typescript:
```
import * as flatten from "flatten-js";
```

**Comment by SamuelQZQ** [comment]
My problem has been solved. I think it's nothing about this library, but my own fault. Maybe this issue can be closed?

**Comment by alexbol99** [comment]
I am also not so experienced with TypeScript but the last suggestion seems correct for now. Later I am planning to redesign the library to es6 modules, then TypeScript support will be more straightforward.
