### ISSUE TITLE
ray and segment intersect

### ISSUE THREAD

**Issue by itfanr** [alexbol99/flatten-js#151]
![image](https://github.com/alexbol99/flatten-js/assets/4652694/19944cbc-cc1c-4232-8f0e-c965104934ef)
Given a line segment and  a ray with the start point and direction vector,  calculate the intersection  point.
The code is as follows: 
```

    let s = segment(point(636, 281.5), point(336, 281.5));

    let r = ray(point(486, 271), vector(71.147335, 70.2713));

    let ip = s.intersect(r);

    if (ip.length > 0) {
      console.log(ip[0].x, ip[0].y);
    }

```

The expectation of this code is to output the intersection point. But I cannot get it.

Can someone help me?

**Comment by alexbol99** [comment]
Hi, @itfanr 
According to my sketch the ray directed not as you expected:
![image](https://github.com/alexbol99/flatten-js/assets/6965440/6ef009cb-a041-4738-b12c-38da166879a7)
See https://observablehq.com/@alexbol99/ray-and-segment-intersect-151
This is definitely wrong, ray supposed to be directed to the right of the normal vector.
I will check this.
You may help me to check if you want

**Comment by itfanr** [comment]
I am a new js user.  I  will try to fix it.  Thank you for your attention to this issue.

**Comment by alexbol99** [comment]
@itfanr ,
Actually there is no mistake.
Simply this library makes an assumption that "y"-axis goes upwards, like in math.
In the image "y"-axis usually goes downwards, which makes it look like in mirror.
In order to get result that you expected, you have to invert vector to be `vector(-71.147335, -70.2713))`:

<img width="514" alt="image" src="https://github.com/alexbol99/flatten-js/assets/6965440/540dcc7f-ca62-4c2c-9aab-a4844f9e0399">

**Comment by itfanr** [comment]
@alexbol99  Thank you. I think I need to check the coordinate system and add some transform.

**Comment by itfanr** [comment]
```
    let s = segment(point(336, -281.5), point(636, -281.5));

    let r = ray(point(486, -271), vector(71.147335, -70.2713));

    let ip = s.intersect(r);

    if (ip.length > 0) {
      console.log(ip[0].x, ip[0].y);
    }

```

I calculated in third quadrant and got the interesct intersection (475.6292861847882, -281.5)
