### ISSUE TITLE
Errors export

### ISSUE THREAD

**Issue by edemaine** [alexbol99/flatten-js#157]
The `Errors` class is documented, but doesn't seem to be exported correctly. Instead of being a class, it's an object with `default` property that is the class. The ESM code looks OK, so it's probably a bundling bug...

Also, the `Errors` export is missing from the `.d.ts` file.

Context: I think `Errors` is useful for detecting that we got a division-by-zero error instead of something else.

**Comment by alexbol99** [comment]
Fixed in v1.4.6
