### ISSUE TITLE
Cannot cut polygon with MultiLine

### ISSUE THREAD

**Issue by metehan-coone** [alexbol99/flatten-js#159]
**Edit: Fixed in v1.5.0 [notebook example](https://observablehq.com/@alexbol99/cut-polygon-with-multiline-159)** ✅

I want to cut a polygon with a polyline, I tried to proceed similarly to the structure in your [notebook example](https://observablehq.com/@alexbol99/cut-polygon-with-line), but I am facing this problem

```js
const polygon = new Polygon([
    point(20, 20),
    point(60, 20),
    point(60, 60),
    point(20, 60),
  ]);
  const segment = new Segment(point(20, 20), point(40, 40));
  const ip1 = segment.intersect(polygon);
  const ip_sorted1 = segment.sortPoints(ip1);

  const segment2 = new Segment(point(40, 40), point(50, 40));
  const ip2 = segment2.intersect(polygon);
  const ip_sorted2 = segment2.sortPoints(ip2);

  const segment3 = new Segment(point(50, 40), point(60, 60));
  const ip3 = segment3.intersect(polygon);
  const ip_sorted3 = segment3.sortPoints(ip3);

  // console.log(ip1, ip2);

  const multiLine = new Multiline([segment, segment2, segment3]).split([
    ...ip_sorted1,
    ...ip_sorted2,
    ...ip_sorted3,
  ]);
  const polygonParts = polygon.cut(multiLine);
```

![image](https://github.com/alexbol99/flatten-js/assets/113349085/d267c8ca-3875-4daa-8c63-726f1261a1ed)

**Comment by alexbol99** [comment]
I reproduced this bug. Method `cut` is incomplete, I need to fix it.

**Comment by metehan-coone** [comment]
> I reproduced this bug. Method `cut` is incomplete, I need to fix it.
Can you close this issue when you fix the bug so I can be notified

**Comment by metehan-coone** [comment]
> I reproduced this bug. Method `cut` is incomplete, I need to fix it.

Can you close this issue when you fix the bug so I can be notified

**Comment by metehan-coone** [comment]
Has there been any change in the usage of the function or is it used as before?
