### ISSUE TITLE
Can I merge duplicated edges and merge faces in Polygon?

### ISSUE THREAD

**Issue by mathedu4all** [alexbol99/flatten-js#162]
![Screenshot from 2024-01-23 15-45-07](https://github.com/alexbol99/flatten-js/assets/11254711/81e0dfad-8341-443e-a515-6835c6944a59)

For example, can i construct the cross shape as polygon with 5 faces.  and use some algorithm to merge these 5 faces as one face. 

This is not a bug, but to check if this feature can be accomplish theoretically?

**Comment by alexbol99** [comment]
Hi, @mathedu4all,
Not exactly what you describe, but you can create 5 polygons and then unify them.
If you already have one polygon with 5 faces, you can do following:
```javascript
import {Polygon, BooleanOperations} from "@flatten-js/core"

let parts = polygon.toArray()
let polygon1 = new Polygon()
for (const part of parts) {
    polygon1 = BooleanOperations.unify(polygon1, part)
}
```

In the resulted polygon duplicated edges will be eliminated

**Comment by mathedu4all** [comment]
Forgive me ignoring the 'unify' method, thanks a lot for your great contribution.

**Comment by alexbol99** [comment]
If it works for you, @mathedu4all , that is great!
Thank you for collaboration
