### ISSUE TITLE
Segment Wrong points after rotate?

### ISSUE THREAD

**Issue by SpaceNinjaApe** [alexbol99/flatten-js#164]
Following code 
```
let l1 = new Segment(
    new Point(-200,0),
    new Point(200,0)
)
console.log(`middle: ${l1.middle().x}, ${l1.middle().y}`)
console.log(`start : ${l1.start.x}, ${l1.start.y}`)
console.log(`length: ${l1.length}`)
console.log()
console.log("rotate(90)")
l1 = l1.rotate(90)
console.log()
console.log(`middle: ${l1.middle().x}, ${l1.middle().y}`)
console.log(`start : ${l1.start.x}, ${l1.start.y}`)
console.log(`length: ${l1.length}`)
```

Gives me following output:
```
middle: 0, 0
start : -200, 0
length: 400

rotate(90)

middle: 0, 0
start : 89.61472322583404, -178.79933272011158
length: 400

```

I would expect:

```
middle: 0, 0
start : -200, 0
length: 400

rotate(90)

middle: 0, 0
start : 0, 200
length: 400
```

Am i missing something? Even with specifying the center for Rotation, it still gives me unexpected outputs.

**Comment by alexbol99** [comment]
Hi, @SpaceNinjaApe ,
Sorry, but you are missing two points:
1) Angle is in radians
2) Y-axis oriented upwards
So, if you rotate segment by angle Math.PI/2 (positive angle rotates counter clockwise), the result will be something like:


```javascript
l1 = l1.rotate(Math.PI/2)
```
`start : -1.2246467991473532e-14, -200`

Best,
Alex

**Comment by SpaceNinjaApe** [comment]
Thanks for the Reply @alexbol99 ,
okay i didnt now about the radians

But shouldnt `l1.rotate(Math.PI/1)` result in the exact same oposite Position ?

Theres always a slight difference to what i expect. Probably due to the nature of PI? How to deal with this? Round / Floor?

**Comment by alexbol99** [comment]
Float calculations always end with small inaccuracy.
You should use rounding

**Comment by SpaceNinjaApe** [comment]
Alright Thanks! keep up the good work lad!
