### ISSUE TITLE
Vector.add(Point) should return a point not a vector

### ISSUE THREAD

**Issue by DonaldDuck313** [alexbol99/flatten-js#167]
If I run the following code in the Javascript console:

```javascript
new Vector(0, -1).add(new Point(5, 5))
```

It returns

```none
Vector {x: 5, y: 4}
```

I would expect it to return a point. I need to translate a point by a vector and get a new point, how do I do that?

Also, in general, functions for converting between points and vectors would be very useful. It would be nice if you could add a `toPoint` method to the Vector class or something equivalent.

**Comment by edemaine** [comment]
I'm guessing `new Point(5, 5).add(new Vector(0, -1))` will do what you what. I agree that the order probably shouldn't matter though; a point plus a vector should be a point.

**Comment by alexbol99** [comment]
Function  ```add``` in class ```Vector``` is supposed to summarize two vectors.
It defined as following
```javascript
add(v: Vector): Vector;
```
If you want to translate point by vector, use ```translate``` method of point:
```javascript
const translated_point = new Point(5, 5).translate(new Vector(0, -1))
```
The result will be a ```Point```

**Comment by DonaldDuck313** [comment]
> If you want to translate point by vector, use `translate` method of point:
> 
> ```js
> const translated_point = new Point(5, 5).translate(new Vector(0, -1))
> ```
> 
> The result will be a `Point`

Thanks, I didn't know about that. It's not in the [documentation for the Point class](https://alexbol99.github.io/flatten-js/Point.html), could you please add it?

**Comment by alexbol99** [comment]
Translate method and other transformations are part of the Shape base class, all classes are inherited from it. So in the docs they are also in Shape, because docs are auto generated.
