### ISSUE TITLE
`length` and `pointAtLength` for multiline

### ISSUE THREAD

**Issue by stanch** [alexbol99/flatten-js#182]
I have a multiline that consists of two segments and an arc (and potentially a more complex one in the future), and it would be great to be able to use `length` and `pointAtLength` for it, instead of manually going through the constituent parts.

A counter-argument could be that multilines can contain rays, which are infinite. However:
* There is already some logic with `setArcLength` that seems to be setting the stage for `pointAtLength`
* I think `svg` and `dpath` would not support rays either?

**Comment by alexbol99** [comment]
Implemented in v1.6.1
