### ISSUE TITLE
Intersection between a line and a multiline

### ISSUE THREAD

**Issue by stanch** [alexbol99/flatten-js#183]
I have a multiline with two segments and an arc (potentially, more complex in the future) and would like to intersect it with a line. This is, of course, a matter of intersecting the line with each edge one by one (and removing duplicates that result from parts of the multiline overlapping).

There are already methods for intersecting a line with each shape that can go into a multiline, so it feels like an omission that `Line`’s `intersect` method does not support multilines.

**Comment by alexbol99** [comment]
Implemented in v1.6.1
