### ISSUE TITLE
"Drop-in geometry library" concept

### ISSUE THREAD

**Issue by GregRos** [alexbol99/flatten-js#19]
I have a suggestion for this project. 

I've recently tried working with an SVG graphics library, only to realize it can't really manipulate vectors very well on its own. I've actually noticed this is a theme among many graphics libraries. 

The best in terms of 2d geometry is (by far) `paper.js`, but not everyone can use that library or wants to (it's a canvas library, first of all, and sometimes you might want to specifically use an SVG library). Also, even that library doesn't really have a complete toolset.

So I came up with this concept of a 2d geometry library that you can "drop-in" and use with other graphics libraries that actually do the rendering. The idea is to have lots of conversions (sometimes implicit ones) to and from different formats. This includes for lines, matrices, vector/point/complex numbers, etc.

I did a bit of work on it, and you can see the API I came up with here, including some implementations for things: https://github.com/GregRos/dropin-geometry

But I figured that there are lots of 2d geometry libraries for JS, it's a lot of work to make one, and there's no point if you can just add that functionality to other libraries. 

Do you think this kind of thing is a good fit for this library?

**Comment by alexbol99** [comment]
Hello @GregRos,
I think you raised an interesting point.
I would like to discuss it in private message.
Please send me your email to alexbol99@gmail.com
Thanks,
Alex

**Comment by alexbol99** [comment]
Close as not planned to do
@GregRos if you still think it is relevant, you may open discussion
