### ISSUE TITLE
Polygon editing with flatten-js

### ISSUE THREAD

**Issue by metehan-coone** [alexbol99/flatten-js#191]
Hi @alexbol99 , I am developing a data labeling tool and there is a feature in this tool where I can draw polygons. What I want is basically to edit the polygon by starting at one point of the polygon, drawing another Line, and terminating that Line at another point of the polygon. 

I currently use 2 different methods for this, one is to enlarge the polygon from the outside and the other is to cut the polygon from the inside. I use the Polygon.cut() method in flatten-js for this process, but as far as I understand with this method, I can only cut with the points inside the polygon. What I want to do is to edit the polygon with Multiline, which I created by giving points from both inside and outside. Is there any other method you can suggest?

![polygon-edit](https://github.com/user-attachments/assets/f1d61967-29cb-4c71-90b5-5a7f79d9f474)

**Comment by alexbol99** [comment]
Hi, @metehan-coone ,
Interesting task
I see it like this:
1) close the new multiline (white) with the relevant part of the existing polygon (blue), and create a new polygon
2) subtract the old polygon from the new polygon
**flatten-js** doesn't have a built-in method to do the first part, you have to implement it in your code

**Comment by metehan-coone** [comment]
Thanks for answering. It looks useful
