### ISSUE TITLE
broken with node v6.14.2

### ISSUE THREAD

**Issue by sacketty** [alexbol99/flatten-js#2]
our platform has switched from node v6.11.5 -> v6.14.2
We can't use flatten-js anymore

> // require package
let Flatten = require('flatten-js');

 generates an error:

> ./workspace/Electron/idscan-electron/node_modules/flatten-js/classes/point.js:232
            let {r, stroke, strokeWidth, fill, ...rest} = attrs;

any clue?
Rgds

**Comment by alexbol99** [comment]
Indeed, support for spread operator in object literals, like { ...rest }, was broken in node v6.14.
It was restored later. In the latest version (I took v8.11.1) it works fine.

See discussion here:
https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread

Best regards,
Alex Bol

**Comment by alexbol99** [comment]
Problematic code removed some versions ago
Issue closed.
