### ISSUE TITLE
Box rotate method not implemented

### ISSUE THREAD

**Issue by bertyhell** [alexbol99/flatten-js#202]
I see that the Box roate() method is not supported
https://alexbol99.github.io/flatten-js/Box.html#rotate
```
rotate(angle, center)
Box rotation is not supported Attempt to rotate box throws error
```

Can i just add this method by rotating all the points?
Or does this have a bigger impact on other functions like intersecting shapes and merging shapes?

if not, i can open a PR for this.

**Comment by romgrk** [comment]
Box doesn't represent a rectangle, it represents an axis-aligned bounding box. If you're looking for a rectangle, you should instead use a polygon. You could create a child class of `Polygon` to facilitate working with rectangles, similar to [this](https://github.com/romgrk/2d-geometry/blob/master/src/classes/Rect.ts).

**Comment by bertyhell** [comment]
Ah, ok, great
I'll do that
