### ISSUE TITLE
Create vector by ps and direction

### ISSUE THREAD

**Issue by ProtonGustave** [alexbol99/flatten-js#21]
What about add ability to create vector from start point and direction(angle)? It's could be handy.

**Comment by alexbol99** [comment]
Yes, it makes sense. I will add this option.

**Comment by alexbol99** [comment]
Vector is defined by direction and magnitude
If we have a direction given by angle, we can define, for instance, unit vector (cos(a), sin(a)).
Start point is irrelevant here.
I will close this issue with no action.
