### ISSUE TITLE
Center of polygon

### ISSUE THREAD

**Issue by schelmo** [alexbol99/flatten-js#22]
is there a good way to get the center of a polygon (or a face)?

**Comment by alexbol99** [comment]
Yes, like this:
```
const c = polygon.box.center
```
This will return the center of the bounding box, if this is what you mean.

Same is for the faces:
```
const array_of_centers = [...polygon.faces].map( face => face.box.center )
```

Please take into account that ```box``` is a getter function and not  a property and will be calculated in any call, that may be expensive

You can find usage of this here:
https://observablehq.com/@alexbol99/collision-detection

**Comment by schelmo** [comment]
ah sure. thanks!
