### ISSUE TITLE
Allow other shapes to be passed into the PlanarSet.search function

### ISSUE THREAD

**Issue by frastlin** [alexbol99/flatten-js#25]
Hello,
I am trying to make a walking algorithm where I have old_x, old_y, new_x, and new_y, and I need to check if there are items between those points.

Plane has a great check point function, but being able to only pass in a bounding box means I need to not use Plane for checking a line, and instead iterate through all the objects and use Line.intersect, which defeats the reason for having a plane in the first place.

So I think it would be very nice to have just one search function that could take a point, bounding box, polygon, line, circle, or any shape, and run the respective intersect functions on all the polygons.
You could make a point that shapes other than point and box are slower, but in my case, it doesn't matter.
Thanks,

**Comment by alexbol99** [comment]
Hello. @frastlin ,

For all shapes other than line the PlanarSet object suggests a search by bounding box, and than you have fine check of intersection. For the line it is obviousely not the case.
Do you need specifically a function that find all shapes in PlanarSet that intersect with a line, kind of plane sweep line algorithm? 

Thanks,
Alex

**Comment by frastlin** [comment]
Yes. I'm also not sure if I like the bounding box either. The bounding box function doesn't work if the polygon has holes or is a multipolygon. It makes the search faster, but then results need to be filtered again.
I'm debugging a function that should use the intersect functions to return searched shapes.

**Comment by frastlin** [comment]
OK I have a problem and I'm not sure if it is me or Flatten.
I have a line that seems to be intersecting with points on a polygon it shouldn't be. I passed in both a vector and points, but I still get odd results. It looks like the line does not have a length. Here is my code:

	const poly = new Polygon()
	poly.addFace([
		new Point(1,1),
		new Point(5,1),
		new Point(5,5),
		new Point(1,5)
	])
	
	const intersectLine = new Line(new Point(3,5), new Vector(new Point(3,5), new Point(3,6)))
	const v1 = new Vector(new Point(6,1), new Point(6,2))
	const parallelPolyLine = new Line(new Point(6,1), v1)
	const perpLine = new Line(new Point(6,2), new Vector(new Point(6,2), new Point(7,2)))
	console.log(intersectLine.intersect(poly)) //This returns (5,5), (5,5), (1,5), (1,5). Why are there 4 points, and none of those points intersect the line from (3,5),(3,6)? I would expect one point, 3,5.
	console.log(parallelPolyLine.intersect(poly)) // This is the odd one. Why are there 4 points? (1,1),(5,1),(5,1),(1,1)?
	console.log(perpLine.intersect(poly)) // This line shows that the line is not extending longer than the vector, so I'm completely lost.
	console.log(v1.length) // Shows the vector to the betweenLine is 1
	console.log(v1.slope) // shows the vector to the betweenLine is facing 90 degrees, which is parallel to the polygon.


If I pass the points from the vector into the Line directly, then it looks like the lines go on forever, so the perpLine and intersectLine have an intersect point, and parallelPolyLine does not. But I need my lines to have a length. Do you know how to solve this problem?

**Comment by frastlin** [comment]
OK, segment is what I was looking for. I'm going to close this, because I have a problem with segments and planar search.
