### ISSUE TITLE
planarSet.search does not handle inbetween multipolygons or holes with polygons

### ISSUE THREAD

**Issue by frastlin** [alexbol99/flatten-js#26]
Hello,
If I do the planarSet.search function and the box I pass in is in the hole of a polygon, or between two parts of a multipolygon, it returns true.
Here's the code:

	const plane = new PlanarSet()
	const poly = new Polygon()
	poly.addFace([
		new Point(1,1),
		new Point(5,1),
		new Point(5,5),
		new Point(1,5)
	])
	poly.addFace([
		new Point(8,1),
		new Point(8, 4),
		new Point(11,4),
		new Point(11,1)
	])
	
	//Hole face
	poly.addFace([
		new Point(10,2),
		new Point(10,3),
		new Point(9,3),
		new Point(9,2)
	])
	
	plane.add(poly)
	
	//The lines that we pass to the search function
	const intersectLine = new Segment(new Point(3,5), new Point(3,6))
	const parallelLine = new Segment(new Point(6,1), new Point(6, 2)) // Should be empty, but has poly
	const perpLine = new Segment(new Point(6,2), new Point(7,2)) // should be empty, but has poly
	const insideLine = new Segment(new Point(2,2), new Point(2,3))
	const inHoleLine = new Segment(new Point(9.5,2.5), new Point(9.9, 2.5)) // should be empty, but it has poly
	
	//Function to test the search function
	function t(l){
		return plane.search(l)
	}
	
	//print the results of the search function to the console
	console.log(t(parallelLine)) // should be empty
	console.log(t(perpLine)) // should be empty
	console.log(t(intersectLine)) // should have the polygon
	console.log(t(insideLine)) // should have the polygon
	console.log(t(inHoleLine  )) // should be empty

**Comment by alexbol99** [comment]
Hello, Brandon @frastlin 

As far as I understand, you need functionality that checks all possible relations between shape and polygon. This functionality still not exist in the library. It is my number one priority in the list of things to be added, I have plans to do it soon.

But when it will be added, I am not sure it will be a part of a PlanarSet. PlanarSet only provides a coarse search based on bounding boxes. I think for most applications this is enough.

Best regards and thank you for cooperation,
Alex Bol

**Comment by frastlin** [comment]
Awesome! I think you could add it to a new method called "advancedSearch" or something to that nature that will be slower.

**Comment by alexbol99** [comment]
Hello @frastlin ,
It took some time to implement this functionality.
I added methods under namespace ***Relations*** that can check any type of relationship between shapes, in your case between segment and polygon (release 1.2.2).
Now it is possible to filter search results using relation check:
```javascript
  let {PlanarSet, Relations} = Flatten;  
  const plane = new PlanarSet()
  
  plane.add(poly)
  
  // Function to test the search function
  function t(l){
    return plane.search(l).filter( shape => Relations.intersect(l, shape) )
  }

  // print the results of the search function to the console
  console.log(t(intersectLine)) // should have the polygon
  console.log(t(parallelLine)) // should be empty
  console.log(t(perpLine)) // should be empty
  console.log(t(insideLine)) // should have the polygon
  console.log(t(inHoleLine  )) // should be empty
```

If you need you can use more fine tuning, for example:
 ```Relations.touch(l,shape)``` will match only ```intersectLine```,
```Relations.inside(l,shape)``` will match only ```insideLine```

See also this notebook: https://observablehq.com/d/fc93adb78c6dcb20
Best regarads,
Alex
