### ISSUE TITLE
provide typescript definition file

### ISSUE THREAD

**Issue by goldenass** [alexbol99/flatten-js#3]
Can you please provide a @types / flatten-js package?
If you are interested in adding it as a project asset I can contribute to it.

**Comment by alexbol99** [comment]
Currently typescript is not in my focus.
Static type checking is great and I understand it may contribute a lot, but my intention is to provide package that works "as is" without any compilation.
I'm afraid that additional .ts files may a bit confuse.
Thank you for your suggestion.
Let me know if you think different.

**Comment by rtm** [comment]
@alexbol99 I've just finished a review of 2D geometry packages and this is a great match for me. Thanks for your work on this.

And yes, I too want a TypeScript definition files. I think you may have misunderstood the question, or not fully understood what it means to create a TypeScript definition file. No-one is asking you to change your code, or rewrite it in TS, or introduce a transpilation step, or anything else. They're just asking for a TypeScript definition file (`.d.ts`) so TS can typecheck *their* code which calls your library from TS. This will confuse no-one. People not using TS can just ignore it. People who do use TS will be extremely grateful for it.

Of course, there's no need for you do do this. Anyone could write the `.d.ts` file, and either publish it themselves as `@types/flatten-js`, or issue a pull request to you to have it merged into the main repo. I'd be glad to do this conceptually, but it'd have to wait until I found a bit of time.

**Comment by alexbol99** [comment]
Thank you @rtm that you appreciate my efforts.
Yes, maybe I underestimate the importance of this issue. Frankly I have very basic knowledge about TypeScript, so any help will be welcomed. I will try to make time to implement this.

**Comment by rtm** [comment]
It would be like something like this.
Completely untested/unverified (will tweak it as I move along).
I need to define some of the manifest constants too.
Once this is installed in the proper way (either by merging it into the repo, or separately npm-installing a `@types/flatten-js` repo that someone publishes on npm's DefinitelyTyped repo, you should be able to do

    import Flatten from "flatten-js";

and everything will work.

**Comment by alexbol99** [comment]
> It would be like something like this

Sorry, @rtm Bob Myers, I don't understand, like what? have you sent me some file?

**Comment by rtm** [comment]
@alexbol-fls Sorry, I forgot the attachment, now attached to my post above.

**Comment by alexbol99** [comment]
Now I see. Thank you

**Comment by alexbol99** [comment]
Typescript definition file was added in version v0.6.0.
This is my first time I do such a job, so, @rtm, would be nice if you can review if it works as expected. Thank you, Mr.Bob Myers, for your cooperation, I used the file you have sent me for starting.

**Comment by alexbol99** [comment]
Thank you @rtm, you pull request was integrated.
I will keep this issue opened for any bugs/questions regarding typescript definition.

**Comment by wikywin** [comment]
![image](https://user-images.githubusercontent.com/4850368/69113673-9b130380-0abe-11ea-914c-09634bb93818.png)

**Comment by wikywin** [comment]
![image](https://user-images.githubusercontent.com/4850368/69113684-a6fec580-0abe-11ea-8d0b-37e81c147854.png)

Hi, I found there's some bugs in  some definition file index.d.ts as displayed above. please fixed it.
you may test it in typescript project firstly

**Comment by wikywin** [comment]
![image](https://user-images.githubusercontent.com/4850368/69113787-fb09aa00-0abe-11ea-97c5-1fb30311eaea.png)

Hi, I found there's some bugs in definition file index.d.ts as displayed above. please fixed it. in order to use it properly, now i have to comment out add, remove insert.
you may test it in typescript project firstly

**Comment by alexbol99** [comment]
Problem with typescript definition (incompatible overriding) fixed in @flatten-js/core v1.1.0
