### ISSUE TITLE
intersect for box and line or segment doesn't exist

### ISSUE THREAD

**Issue by stocksp** [alexbol99/flatten-js#30]
Box isn't a shape inside the intersect method for either segment or line.  So passing a box to their intersect method fails.

I didn't see anywhere the intersectLine2Box(line, box) function was exported. Though its used internally.

I took the three function:  intersectLine2Box, intersectSegment2Line and intersectLine2Line:  They work for what I'm doing..
 
Great library! thanks for all your work!

**Comment by alexbol99** [comment]
Support intersection with box added in v1.0.19.
Now method ```intersect(shape)``` supports shape of type Box for Line, Segment, Arc and Circle.
Method return array of intersection points.
Intersection between Polygon and Box will be added later.
