### ISSUE TITLE
Example for Adding a Tooltip to the Polygon With Data

### ISSUE THREAD

**Issue by frastlin** [alexbol99/flatten-js#33]
Hello,
I am looking at:
https://observablehq.com/@alexbol99/flattenjs-tutorials-polygons
and would like to know if there is any way to add a name attribute to the polygon that can pop up when you move your mouse over the polygon in D3?
I'm using a planerSet with lots of polygons, I managed to get it showing on d3, but now I would like to do actions when the mouse hovers over the polygon.
How would you recommend to do this? It would be helpful if there was a tutorial on how to do that as well.
Thank you,

**Comment by frastlin** [comment]
I would also like to know if I can specify color for different polygons when using the planer.svg function? If not, will iterating through all the polygon shapes and appending them to the d3 view put them in the correct position?

**Comment by alexbol99** [comment]
Hello @frastlin Brandon,

In d3 your can bind array of geom objects to an array of d3 objects using  ```.data(geomArray)``` command. 
If your polygons organised into planarSet, you need to destruct them first into array: ```.data[...planarSet]``` and then each object will be linked to correspondent d3 element.
Then you can listen mouse events to add/remove tooltips.
In this notebook https://observablehq.com/d/b54ad15e444ca81e I created planar set of circles, but I think an idea is the same.
