### ISSUE TITLE
What is the difference between Segment and Line?

### ISSUE THREAD

**Issue by redexp** [alexbol99/flatten-js#37]
Hello, can you please explain what is the difference between these two classes? For me it looks like Segment is same as Line only with more methods.
Also, can you please help me to figure out easy way to change length of segment?
And last one, if there any question can I post them on stackoverflow with tag `flatten-js` (do you watch on them) or it will be easier for you if post questions here?

Thank you!

**Comment by alexbol99** [comment]
Hello Sergii,
By definition line is infinite, while segment is a part of a line between two points. I would not say they are the same,  I don't see too many common between them. 
On you second question, can you give in example what you expect from the function that "change the length of the segment"? Then it will be easier to me to give you advice.
And you may ask questions any way you like, even in direct email.
Best regards,
Alex

**Comment by redexp** [comment]
Something like 
```javascript
var seg = segment([10, 10, 100, 100]);
seg.length // 127.27922061357856
seg.length = 100;
seg.start // {x: 10, y: 10}
seg.end // {x: 70.71067811865476, y: 70.71067811865476}
```
I saw `length` is getter, so make it setter should be logical

**Comment by alexbol99** [comment]
Hi, Sergii,

This logic assumed that start point is not changed.
Another logic may assume that it works like scale when central point not changed, or even  scaling with respect to any arbitrary point. So this is beyond simple setter to change length.
As for your case, I would suggest something like this:
```javascript
let vec = new Vector(segment.start, segment.end);
vec = vec.normalize().multiply(length);
let newEnd = segment.start.translate(vec);
let newSegment = new Segment(segment.start, newEnd)
```

**Comment by redexp** [comment]
Thanks a lot!
