### ISSUE TITLE
Support for basic vector operations

### ISSUE THREAD

**Issue by walmink** [alexbol99/flatten-js#4]
The various `distanceTo()` methods have been of great use to me. Now I wanted to use the library for some basic operations, like adding and subtracting vectors, but I don't seem to find them in documentation or code. The closest thing I can find is `Point.translate()`, but that's tied to `Point` and does not include other vector operations.

Am I missing something, or are these vector operations currently not supported?

**Comment by alexbol99** [comment]
Indeed some basic operations still missing. I will add them soon, it makes sense.

**Comment by walmink** [comment]
Great! Just making sure I wasn't missing something. This library is great for projects that require geometric calculations but no physics simulation; those types of libraries usually come with good geometric methods, but wrapped into the complexity that physics simulations bring.

**Comment by alexbol99** [comment]
We use this library for prototyping and visualization of algorithms for our CAM solutions. And this library is just a a porting from our C library which is running at the field for more than twenty years.
What is your area of interest? You may use my private email alexbol99@gmail.com

**Comment by walmink** [comment]
That's great, thank you @alexbol99!

**Comment by alexbol99** [comment]
Issue closed
