### ISSUE TITLE
Is there a way to find the center point of a shape?

### ISSUE THREAD

**Issue by aalexgabi** [alexbol99/flatten-js#43]
I need to rotate a rectangle (I'm using a polygon to represent it) by using it's center point as pivot. Is there a way to determine the center point of a shape (or at least a polygon)? I didn't find anything in the documentation (maybe it's named differently).

On a side note: I'm not sure that using 0,0 for the rotation center is a good default. What do you think about using the center of the shape that is being rotated by default?

**Comment by alexbol99** [comment]
Hello @aalexgabi ,

Get center of the shape as a center of its bounding box, like this:
```javascript
const center = polygon.box.center
```
I tend to agree with you: set rotation around center as a default maybe better choice.

Best,
Alex

**Comment by aalexgabi** [comment]
@alexbol99 Thank you for the answer. Should we close this?

**Comment by alexbol99** [comment]
Yes @aalexgabi , I closed it
