### ISSUE TITLE
Problem with ray intersection?

### ISSUE THREAD

**Issue by asos-tomp** [alexbol99/flatten-js#48]
I'm sure I'm just doing something stupid, but can anyone shed any light on the below?

[jsFiddle](https://jsfiddle.net/mj1daret/)

```
import { Vector, Point, Ray, Segment } from '@flatten-js/core';
const segment = new Segment(new Point(0, 0), new Point(1, 0));
const origin = new Point(0.5, 0.5);
const vector = new Vector(origin, new Point(0.5, 0.4));
const ray = new Ray(origin, vector);
const intersections = ray.intersect(segment);
```

I would expect the ray (starting at `{ x: 0.5, y: 0.5 }`, with a vector heading negative y) would intersect with the segment (`{ x: 0, y: 0 }` to `{ x: 1, y: 0 }`) at a point on that segment: `{ x: 0.5, y: 0 }`.

But `intersections.length === 0`.  What am I doing wrong?

![image](https://user-images.githubusercontent.com/10725179/86356950-09c75a80-bc65-11ea-8385-a9c6c8bacdb4.png)

**Comment by alexbol99** [comment]
Hello @asos-tomp 

In the ray constructor ```new Ray(origin, vector)```  ***vector*** is ortogonal to ray direction, so that points on a ray fit equation:
```mat
 (x - origin)*n = 0
```
If you define ray like this:
```javascript
new Ray( new Point(0.5,0.5), new Vector(1,0) )
```
then you will get intersection point at (0.5, 0)

Best regards,
Alex Bol

**Comment by erikpols** [comment]
Hello Alex,
Love the library so far. However this took me 3+ hours to figure out, it is not a very intuitive thing. Would it be a bad solution to accept the ray direction in the constructor instead and rotate the vector to do what you want with it?

**Comment by alexbol99** [comment]
Hello @erikpols ,
Sorry for making waste you time.
I might change it because I realized that many people have same intuitive understaning of a ray like you and @asos-tomp .
But I am afraid of doing breaking change for people that already use it in the current way.
I will consider this for the future major version
For a while I just updated documentation for Ray constructor
Best,
Alex

**Comment by erikpols** [comment]
Hi Alex thank you! It's no problem it happens, and I understand if you don't wanna change it for backwards compatibility.
