### ISSUE TITLE
Compile to ES5 before publish to npm

### ISSUE THREAD

**Issue by walmink** [alexbol99/flatten-js#5]
React cannot minify this repository during build, because it hasn't been compiled to ES5. [The React team recommends compiling packages to ES5 before publishing to ES5](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).

Of course, you may have your own needs and reasons for not having it compiled to ES5. I just wanted to inform you that compiling it will make this repository more relevant for React developers. The alternative for React developers is forking it or copying it to project code (both not ideal).

**Comment by alexbol99** [comment]
Yes, I know about this recommendation.
When I built my applications, I went to webpack.config.prod.js in node_modules/react-scripts/config/
and commented out Uglify plugin.
Till now I am running non-minified and waiting for the better plugin that will support ES6. 
Is this workaround acceptable for your project?

**Comment by walmink** [comment]
Thanks for sharing your approach. I considered copying the code into my source code, but that's just too messy. Your suggestion is better and is fine for now: I'm still in development and file size is not my main concern, as I'm planning to release it as a React app wrapped into a native mobile app.

Fingers crossed a better or updated plugin will be available in the near future!

**Comment by alexbol99** [comment]
Since v0.6.2 I will add the package precompiled to es5 (not minified)
It uses commonjs2 format, so the import of the package have to be like following:
```
import Flatten from "flatten-js/dist/flatten.commonjs2"
```
Then you can build you app in production.
No need to switch off Uglify plugin anymore.
See this [demo](https://github.com/alexbol99/flatten-react-demo) project and [here](https://alexbol99.github.io/flatten-react-demo) it is live.

**Comment by alexbol99** [comment]
This request is outdated
