### ISSUE TITLE
BooleanOperations.intersect(a, b) doesn't seem to return correct results

### ISSUE THREAD

**Issue by anvaka** [alexbol99/flatten-js#50]
Here is an observable notebook to play: https://observablehq.com/d/adead0595ff39aa7

``` js
  let {point, BooleanOperations, Polygon} = Flatten;  
  // Create new polygon
  let a = new Polygon([
    point(10,10), 
    point(10, 100),
    point(100, 100), 
    point(100, 10), 
  ]);
  let b = new Polygon([
    point(90,50), 
    point(120, 10),
    point(120, 100)
  ]);
  
  let stage = d3.select(DOM.svg(400, 400));
  stage.html(a.svg() + b.svg() + BooleanOperations.intersect(a, b).svg({fill: 'red'})); 
```

I expect the intersection to be there, but seems like return path is empty:

![image](https://user-images.githubusercontent.com/225407/87209100-9a391700-c2c5-11ea-9c0c-18e99de674db.png)

**Comment by alexbol99** [comment]
Hello @anvaka ,

Polygons in boolean operation should have same orientation.
You can ensure this by adding check like following:

```javascript
if ([...a.faces][0].orientation() != [...b.faces][0].orientation()) {
    a = a.reverse()
}
```
Then you will get expected result.

Best,
Alex

**Comment by anvaka** [comment]
That was it. Thank you!
