### ISSUE TITLE
Intersect and subtract boolean operations fail when passed empty polygons

### ISSUE THREAD

**Issue by OliverColeman** [alexbol99/flatten-js#52]
I get an error when passing an empty polygon as one of the arguments to the intersect or subtract boolean operations. Eg see the console output at https://codesandbox.io/s/late-https-8sjsf?file=/src/index.js

I expected output for intersect to be empty polygon.

I expected output for subtract to be same as the first polygon passed.

If the current behaviour is an error I'm happy to submit a PR.

In my browser console the error looks like:
```
Uncaught (in promise) TypeError: element is undefined
    toArray modules.js:160363
    get edges modules.js:164770
    get shapes modules.js:164778
    clone modules.js:165370
    subtract modules.js:158791
```

**Comment by alexbol99** [comment]
Hello, @OliverColeman ,

Big fixed in release v1.2.9
Now construction of polygon like 
```javascript
const emptyP = new Polygon([]);
```
gives the same result as
```javascript
const emptyP = new Polygon();
```
The result is empty polygon with zero faces.
Then all boolean operations gives correct result.

Thank you,
Alex Bol
