### ISSUE TITLE
Missing variable declaration and instantiation in segment2line method

### ISSUE THREAD

**Issue by walmink** [alexbol99/flatten-js#6]
_(I tried to create a branch commit with pull request with fix, but I don't have permissions)_

Method `segment2line` is missing variable declaration and instantiation for `dist_and_segment`.

**Comment by alexbol99** [comment]
Thank you, fixed it. Will be released tomorrow.

**Comment by alexbol99** [comment]
Fixed in the version 0.4.6

**Comment by alexbol99** [comment]
Issue closed
