### ISSUE TITLE
Is there a way to combine multiple shapes together that are overlapping or touching?

### ISSUE THREAD

**Issue by joshuarobs** [alexbol99/flatten-js#61]
Am I able to have two shapes, where there is some overlap between the two, and somehow combine them into a single custom polygon that combines the two shapes together?

![Frame 21](https://user-images.githubusercontent.com/52946881/95429074-99cc1d00-0995-11eb-90e4-098bab2fe141.png)

In the picture above, if I have the left side, how can I get the right side? Is there some sort of algorithm or simple function to call?

I need this because I'd like to calculate the overall surface area that multiple shapes may take up, in a given box. I know if I just added up surface areas, that there would be errors if there is overlap.

**Comment by alexbol99** [comment]
You need to use method ```unify``` from namespace ```Flatten.BooleanOperations```.
For example:
```javascript
import Flatten from "@flatten-js/core"
const { polygon } = Flatten;
const { unify } = Flatten.BooleanOperations;

const p1 = polygon([[0, 30], [30, 30], [30, 0], [0, 0]]);
const p2 = polygon([[20, 5], [20, 25], [40, 15]]);
const p3 = unify(p1, p2);
console.log(p3.area())
```
You only need to ensure that both operands have same orientation: clockwise or counterclockwise

Best regards
Alex

**Comment by joshuarobs** [comment]
@alexbol99 
Thank you for the example, I find it very helpful

By any chance, is there a function to sort the points of a polygon automatically in clockwise/counter clockwise? This is so that I can automatically have the 2 polygons ready to call in `unify(p1, p2)` as you say, with the same orientation

**Comment by alexbol99** [comment]
Hello @joshuarobs 

You got 6 vertices because `unify` joins two polygons together but does not simplify a result. Original vertices are still there, see picture:
![61](https://user-images.githubusercontent.com/6965440/95582297-1cf77c80-0a43-11eb-9a60-550526362e0e.JPG)

About your first question, you can do this to ensure same orientation:
```
const a = polygon(box(0, 0, 100, 50));               // polygon constructor accepts box, not only points
const b = polygon(box(0, 50, 100, 100));

// reverse second polyon is it has different orientation
if (a.orientation() != b.orientation()) {
     b.reverse()
}

const union = unify(a, b);
console.log('union.vertices:', union.vertices);
```

Best,
Alex

**Comment by joshuarobs** [comment]
@alexbol99 
Thank you again for the clarification!

I think I'll do it your way, when it comes to defining two boxes. My way of calling `toPoints()` seems less efficient than your method.

Also, I have a few questions regarding `unify`:

1. Is there a reason why `unify` doesn't simplify the result?
2. Is there any benefits/disadvantages having extra vertices/not simplifying the result?
3. Is it necessary to even simplify the result, for calculations? (e.g. area, or doing further unions with other polygons)
4. Is there a way to simplify the result?

With regards to 4, I think I found a method to simplify the result, with regards to the 2 boxes as inputs:

````
// ...
const union = unify(a, b);

// Get the points in the middle that need to be deleted
const extraPoints = calculateIntersections(a, b)[0];
// Delete the `extraPoints` found within the array using lodash or `array.filter`
// - Maybe have to copy points into array, then delete from that array, then create a new polygon from those array of points
````

Would finding the common points and deleting them work in more complicated polygons? I personally think it won't and that I'd need a more advanced algorithm to simplify the shape and remove redundant vertices

**Comment by alexbol99** [comment]
Hello @joshuarobs,

Boolean operations do not simplify result because in my opinion this is not their responsibility to do that. I don't want to decide for the user if this vertex redundant for him or not.
Currently the library has no method of polygon simplification. The way you suggest may work but it is not so efficient to recreate polygon many times.
I will add one of simplification algorithms in the future. As a first step I can add a method that enables to remove a vertex and join two edges.

Best regards,
Alex

**Comment by tansanDOTeth** [comment]
> Hello @joshuarobs,
> 
> Boolean operations do not simplify result because in my opinion this is not their responsibility to do that. I don't want to decide for the user if this vertex redundant for him or not. Currently the library has no method of polygon simplification. The way you suggest may work but it is not so efficient to recreate polygon many times. I will add one of simplification algorithms in the future. As a first step I can add a method that enables to remove a vertex and join two edges.
> 
> Best regards, Alex

Has this simplification been added by chance?

**Comment by tansanDOTeth** [comment]
> ```
> const a = polygon(box(0, 0, 100, 50));               // polygon constructor accepts box, not only points
> const b = polygon(box(0, 50, 100, 100));
> 
> // reverse second polyon is it has different orientation
> if (a.orientation() != b.orientation()) {
>      b.reverse()
> }
> 
> const union = unify(a, b);
> console.log('union.vertices:', union.vertices);
> ```

I tried this code and it doesn't seem like the polygon class has an orientation method on it. Is there still a way to do ths?

**Comment by alexbol99** [comment]
Hi, @tansanDOTeth 
Indeed, my mistake, `orientation` is the method of the `face`, not `polygon`.
Usually polygon has more than one face.
If you are sure that both have one face, you can do following:
```javascript
const a_face = [...a.faces][0]
const b_face = [...b.faces][0]
if (a_face.orientation() != b_face.orientation()) {
    b_face.reverse()
}
```

**Comment by tansanDOTeth** [comment]
> Hi, @tansanDOTeth Indeed, my mistake, `orientation` is the method of the `face`, not `polygon`. Usually polygon has more than one face. If you are sure that both have one face, you can do following:
> 
> ```js
> const a_face = [...a.faces][0]
> const b_face = [...b.faces][0]
> if (a_face.orientation() != b_face.orientation()) {
>     b_face.reverse()
> }
> ```

I see! is there a way to achieve what was presented in the original post with this library then? I don't really know polygons well enough to understand the different functions

**Comment by YarekTyshchenko** [comment]
Whichever way I look at it, the vertex order gets messed up

```js
import Flatten, {Polygon} from '@flatten-js/core';

const a = new Polygon(new Flatten.Box(0, 0, 100, 100))
const b = new Polygon(new Flatten.Box(20, 20, 150, 150))
const c = Flatten.BooleanOperations.unify(a, b);

console.log(c.vertices)
```

![2023-12-02-133059_179x174_scrot](https://github.com/alexbol99/flatten-js/assets/185304/2b4679e7-938a-4237-98a5-25b933899c59)

**Comment by YarekTyshchenko** [comment]
Yes! That's it:
![2023-12-02-144403_181x175_scrot](https://github.com/alexbol99/flatten-js/assets/185304/2113fc2e-a406-4119-a72b-a5bdcb965b8b)

Yea it would have been useful to know that `Polygon.vertices` was unordered, it sort of doesn't make sense as you create a polygon from points and order there is very important.
