### ISSUE TITLE
Add a method Polygon::removeVertex()

### ISSUE THREAD

**Issue by alexbol99** [alexbol99/flatten-js#62]
Add a method that enables to remove vertex from polygon and join two edges

**Comment by tansanDOTeth** [comment]
I was looking for a way to simplifying my existing polygon, and this method would have been helpful to have. Otherwise, I would have to manually filter out the vertex and create a new polygon. 

This method would be convenient since there isn't a way to simplify (Related to #61)

**Comment by alexbol99** [comment]
Added in v1.3.10

**Comment by tansanDOTeth** [comment]
> Added in v1.3.10

Has the tag been pushed to github already? I don't see it

**Comment by alexbol99** [comment]
Hi, @tansanDOTeth ,
Sorry, I had to share more details about this
Method name is not `removeVertex`, because vertex in polygon cannot be addressed.
This is `removeEndVertex(edge)`. It merge `edge` with `edge.next` removing vertex between them.
But first you need to locate the edge you want to merge, using `findEdgeByPoint(pt)` method, for example.
I will add code example later
(I reopened this issue for your further comments)
Best,
Alex

**Comment by alexbol99** [comment]
Hi, @tansanDOTeth ,
There was a bug in v1.3.10, please use patch 1.3.12
See example here https://observablehq.com/@alexbol99/example-of-removeendvertex-61
