### ISSUE TITLE
If we are checking if a small polygon is inside a bigger polygon, is using a box faster than a circle?

### ISSUE THREAD

**Issue by joshuarobs** [alexbol99/flatten-js#66]
I want to check if a small shape is inside, or touching a bigger shape. Are there any optimisations, i.e. is it more faster for the program to check the smaller shape if its a square? (Because in programming, a square is only just 4 coordinates, whereas a circle is more complicated).

I know for most simple use-cases, it doesn't matter, and perhaps the accuracy of a circle is better, but for a certain server-side implementation, where every milisecond is key, I'm looking to make some sacrifices in accuracy to make the calculation more faster. Is using a square faster than a circle?

**Comment by alexbol99** [comment]
Hi @joshuarobs, 

Circle in this library is 1 point and radius, while square (box) is 4 digits.
But I think this is irrelevant.
I need to understand your use case better.
If this is a search in the set of shapes under given coordinate with some tolerance, I recommend to use PlanerSet with search index built-in. This index supports rectangular search, and returns all shapes which bounding boxes intersecting with query rectangle. Then you may perform fine (exact) search whether shape is inside.
I think this will give best performance.
But this is my guess, maybe your use case is different.

Thanks,
Alex Bol

**Comment by joshuarobs** [comment]
Hi @alexbol99,

Thanks for the insight! My use case is simply checking whether a circle is inside a single box. I'm not doing any kind of searching, but rather just comparing two simple shapes and seeing if one is inside the other.

It seems PlanerSet is a bit too much for my needs, or I could be wrong.

Thanks

**Comment by alexbol99** [comment]
HI @joshuarobs ,

In this case I think circle check works faster, because it's just to check if center is inside and distance from center to edges is less then radius.

Best,
Alex Bol

**Comment by joshuarobs** [comment]
@alexbol99 

That's odd. My instinct would've thought that square is faster, because it's just checking the bounds of a square, inside another square, using simply less/greater than comparison? A square inside a square would be 2 checks, but a circle inside a square would be 5 checks? (1 for center of circle, then 4 more, for every corner of the square, comparing distance of center point to a corner and checking if distance < radius)

**Comment by alexbol99** [comment]
@joshuarobs 
If your shapes are only circles and squares than you instinct is right
