### ISSUE TITLE
Documentation mistake: BooleanOp

### ISSUE THREAD

**Issue by erikpols** [alexbol99/flatten-js#77]
The documentation refers in different places to the boolean operation namespace as BooleanOp whereas in code it is named BooleanOperations

https://alexbol99.github.io/flatten-js/module-BooleanOp.html#.subtract

also on this page:
https://github.com/alexbol99/flatten-js

`let {unify, subtract, intersect, innerClip, outerClip} = BooleanOp;
`
is not correct

**Comment by alexbol99** [comment]
Documentation issue fixed in patch v1.2.19
