### ISSUE TITLE
Uncaught ReferenceError: Illegal Parameters for Nested Multipolygon

### ISSUE THREAD

**Issue by frastlin** [alexbol99/flatten-js#79]
Hello,
Nested multipolygons from Geojson give the error:
"Uncaught ReferenceError: Illegal Parameters"
when passed to new Polygon().

	const smallPoly = [
		[
			[
				[
					1,
					1
				],
				[
					1,
					2
				],
				[
					2,
					2
				],
				[
					2,
					1
				]
			]
		],
		[
			[
				[
					4,
					4
				],
				[
					4,
					5
				],
				[
					5,
					5
				],
				[
					5,
					4
				]
			]
		]
	]
	
	new Polygon(smallPoly)

Throws the error

**Comment by alexbol99** [comment]
Hello, Brandon,

Parser cannot create polygon because of extra level of nesting.
I don't work with GeoJSON and when I wrote this package I had no intention to be compliant with this format.
But it may be a good idea.
Do you know where I can find the latest specification of GeoJSON?

Best regards,
Alex Bol

**Comment by frastlin** [comment]
Here is the latest version:
https://tools.ietf.org/html/rfc7946

**Comment by alexbol99** [comment]
Hi, @frastlin 
Support for GeoJSON polygons added in the patch v1.2.20
Thank you for cooperation

**Comment by frastlin** [comment]
I haven't tried this yet, but here is the geojson data I'm working with now. Two problems in the old version were duplicate points and nested polygons. Also, it is extremely slow when doing a planerSet search.
[statesWithCases.txt](https://github.com/alexbol99/flatten-js/files/5890259/statesWithCases.txt)

**Comment by frastlin** [comment]
Here is the link to the source for this geojson, you can get a more complex file with the 500K:
https://eric.clst.org/tech/usgeojson/

**Comment by alexbol99** [comment]
Hi, @frastlin ,

I tested your file and it looks ok, see notebook: https://observablehq.com/d/27700cb7cb4e37aa.
I also added removal of zero-length segments when polygon created, in the same version 1.2.20.
So, second issue fixed too.
What are you trying to search? There are only 51 polygons in the set, search should be fast.

**Comment by frastlin** [comment]
I'm searching a segment shape that's of varying lengths.

**Comment by frastlin** [comment]
Did you test all the nearest point and center point functions as well? I've been getting an error with center point, but I have not had time to investigate it. I'm going to download this latest patch.
Thank you!

**Comment by alexbol99** [comment]
Hello @frastlin ,

I am closing this issue.
If you have a problem with center point please report it in a new one.

Thank you,
Alex Bol
