### ISSUE TITLE
Intersect between a line and circle doesn't work

### ISSUE THREAD

**Issue by RedHatter** [alexbol99/flatten-js#8]
If I have a circle and a line passing through I would expect `intersect` to return an array on points where the line passes through the diamater of the circle. As far as I can tell what `intersect` acceally returns is an array of points where the line passes through the bounding box of the circle.

    let center = new Flatten.Point(width / 2, width / 2)
    let circle = new Flatten.Circle(center, width / 3)
    let eighth = new Flatten.Line(center, new Flatten.Vector(-1, 1))
    let points = circle.intersect(eighth)

See this [observable](https://beta.observablehq.com/d/d7334e19572d514b)

**Comment by alexbol99** [comment]
Thank you @RedHatter  for submitting this issue
Bug fixed in version 0.5.3
See this [notebook](https://beta.observablehq.com/@alexbol99/issue-8)
