### ISSUE TITLE
Infinity Loop Error Occurs When unifying polygons

### ISSUE THREAD

**Issue by HualiangLI** [alexbol99/flatten-js#82]
Reproduce with the following link:

https://observablehq.com/@hualiangli/infinity-loop-when-unifying-polygon

**Comment by alexbol99** [comment]
Hello, @HualiangLI ,

Bug fixed in the patch v1.2.21, see https://next.observablehq.com/d/2d71f2dbdf2a518e

Thanks you for cooperation,
Alex
