### ISSUE TITLE
Demo bug in Check inclusion

### ISSUE THREAD

**Issue by IanBellomy** [alexbol99/flatten-js#9]
In the tutorial, [the demo](https://beta.observablehq.com/@alexbol99/flattenjs-tutorials-messing-around) for '3. Check inclusion' breaks in Safari (11.1). Lines outside the circle are colored red. 

<img width="669" alt="screen shot 2018-08-06 at 9 50 36 am" src="https://user-images.githubusercontent.com/17239616/43720342-37ad6a6a-995e-11e8-8498-7144f2d60ae4.png">

**Comment by alexbol99** [comment]
Hi @IanBellomy,
It was a bug in the notebook, library seems ok.
Bug fixed, see notebook updated.
Thank you

**Comment by alexbol99** [comment]
Issue closed
