### ISSUE TITLE
`CircularLinkedList` not exported

### ISSUE THREAD

**Issue by MaikuMori** [alexbol99/flatten-js#90]
These utility classes are useful and should be exported:

 - `CircularLinkedList`
 - `LinkedList`

**Comment by alexbol99** [comment]
Hi @MaikuMori ,

These two structures intended for internal usage, they represent list of edges.
Implementation is not generic, you cannot use them as a list of arbitrary items.
I am not sure that expose them is a good idea.
There are a lot of packages implementing linked list in npm.
Why do we need another one?

Thanks,
Alex

**Comment by MaikuMori** [comment]
Fair enough, I was just playing around with the library, and they would have been useful. I ended up just using an array and simulating a linked list.
